# Use Node.js LTS image
FROM node:18

# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY package*.json ./
RUN npm install

# Copy .env file
COPY .env.production .env

# Copy all files
COPY . .

# Expose the frontend port (default is 3000)
EXPOSE 3000

# Start Next.js in development mode
CMD ["npm", "run", "dev"]
